"""1ドットずつ手で置く方式の、右向き（斜め）キャラ。30×64、見本と同じ体の比率。
文字の表 → 色。外側の輪郭・部品のさかい目の線・白いふちは自動で足す。
"""
from PIL import Image

C = {
    'O': '#3b0a2a',
    'J': '#ffc890', 'H': '#e08a52', 'h': '#b85a36', 'd': '#7a2c2c',                 # 髪
    'S': '#f6cfb2', 's': '#eaa282', 'k': '#b8655a', 'r': '#ec8f84',                 # 肌
    'E': '#f7f6e6', 'e': '#3a1a2a', 'f': '#8a4a3a',                                 # 目
    'C': '#f6eedb', 'c': '#c8b0a0',                                                 # ヘアピン
    'W': '#f6eedb', 'w': '#d6bfa6', 'R': '#c84a3a', 'Q': '#8a2a30',                 # ブラウス・リボン
    'Z': '#7cc0bc', 'T': '#4f9a9a', 't': '#35717a', 'u': '#23495a',                 # 上着
    'X': '#8fd0c8', 'A': '#5aa8a6', 'a': '#3a7a84',                                 # そで
    'L': '#7a3f2a', 'Y': '#e8c060', 'l': '#6e3a26',                                 # ベルト・ひも
    'M': '#b8743e', 'm': '#6e3a26', 'y': '#e8c060',                                 # かばん
    'P': '#7d4f8f', 'p': '#573468', 'o': '#43285a', 'V': '#f6eedb', 'v': '#d6bfa6', # スカート
    'g': '#5a4c58', 'G': '#3c303e', 'n': '#74647a',                                 # タイツ
    'K': '#d89458', 'B': '#b0683a', 'b': '#6e3628',                                 # ブーツ
}
ART = r"""
..............................
..............................
..............................
...........hhhh...............
.........hhHHhhhd.............
........hHJJHhhhhd............
.......hHJHHhhhhhhd...........
......hHJHhhhhHhhhhd..........
......hHHhhhdhHHhhhhd.........
.....hHHhhhdhhhhdhhhhd........
.....hHhhhdhhhhdhhhShhd.......
....hHhhhdhhhhdhhSSShSd.......
....hHhhhCChhhSSSSSSSShd......
...dhhhhhhhhhhdSSSSSSSS.......
...dhhhhhhhhhdsSSSSSSSSS......
...dhhhhhhhhhdsSSSSSSSS.......
...ddhhhhhhhdssSSSSSSS........
....dhhhhhhdksSSSSSSs.........
....ddhdhhd.kssSSSss..........
.....d.d.d...kksss............
..............kkk.............
..........uTTTsRQRTt..........
.........uTTTTTWQWTTt.........
........uTTZZTTWWWAAa.........
.......uTTZTTTtWWwAAAa........
......uuTTTTTttWWwAXAAa.......
.....uutTTTTttWWwAXAAa........
....uutttTTTttWwwAAAa.........
....uuutttttttWwwAAaa.........
.....uuSStttttuWwAAaa.........
......SSsLLLLLLYLAAa..........
......ksPPPPPPPPPAaa..........
.......PPPPPPPPPPPSSs.........
......PPPPPPPPPPPPsSk.........
.....PPPPPoPPPPPPPpp..........
.....PPPPPoPPPPPPPpp..........
....PPPPPPoPPPPPPoPpp.........
....PPPPPoPPPPPPPoPpp.........
....PPPPPoPPPPPPoPPppp........
...PPPPPPoPPPPPPoPPppp........
...PPPPPoPPPPPPPoPpppp........
...PPPPPoPPPPPPoPPpppp........
..PPPPPPoPPPPPPoPPppppp.......
..PPPPPoPPPPPPPoPpppppp.......
..pPPPPoPPPPPPoPPpppppp.......
..ppPPPoppPPPPoppppppp........
...VVVVVVVVVVVVVVVvvvv........
.......GGGG....gggg...........
.......GGGG....gggg...........
......GGGG.....gggg...........
......GGGG......gggg..........
......GGGG......gggg..........
.....GGGG.......gggg..........
.....GGGG.......nggg..........
.....GGGG........gggg.........
....KKKKK.......KKKKK.........
....bBBBb.......bBBBb.........
....bBBBb.......bBBBBb........
....bBBBbb......bBBBBbb.......
...bBBBBBbb.....bBBBBBBb......
...bbbbbbbbb....bbbbbbbbbb....
..............................
..............................
"""
DETAIL = [
    # 目（まつげ・白い光・ひとみ）、まゆ、ほほ、口
    (18, 13, 'O'), (19, 13, 'O'), (20, 13, 'O'), (21, 13, 'O'), (22, 12, 'O'),
    (18, 14, 'O'), (19, 14, 'E'), (20, 14, 'e'),
    (18, 15, 'O'), (19, 15, 'e'), (20, 15, 'f'),
    (19, 16, 'O'), (20, 16, 'O'),
    (19, 12, 'd'), (20, 12, 'd'), (21, 12, 'd'),
    (17, 17, 'r'), (18, 17, 'r'), (20, 17, 'k'),
    (16, 1, '.'), (15, 2, 'h'), (16, 2, 'h'), (17, 1, 'h'),          # はねた毛
]
# ななめがけのひも（右肩 → 左の腰）とかばん
STRAP = [(16, 22), (15, 23), (14, 24), (13, 25), (12, 26), (11, 27), (10, 28), (9, 29)]
BAG = """
mMMMMm
mMyyMm
mMMMMm
mMMMMm
mmmmmm
"""
BAG_AT = (3, 34)

rows = [r.ljust(30, '.') for r in ART.strip('\n').split('\n')]
H, W = len(rows), 30
g = [list(r) for r in rows]
for x, y, c in DETAIL:
    g[y][x] = c
for x, y in STRAP:
    if g[y][x] in 'TtuZWw':
        g[y][x] = 'l'
for j, r in enumerate(BAG.strip('\n').split('\n')):
    for i, c in enumerate(r):
        g[BAG_AT[1] + j][BAG_AT[0] + i] = c

# 2×2の塊で明暗のまだらを足す（見本の「塗りムラ」）
import random
rng = random.Random(7)
MOTTLE = {'h': ('H', 'd'), 'T': ('Z', 't'), 'P': ('P', 'p'), 'A': ('X', 'a')}
for by in range(0, H, 2):
    for bx in range(0, W, 2):
        cells = [(bx + i, by + j) for i in (0, 1) for j in (0, 1) if bx + i < W and by + j < H]
        base = [g[y][x] for x, y in cells]
        if len(set(base)) != 1 or base[0] not in MOTTLE:
            continue
        lite, dark = MOTTLE[base[0]]
        r = rng.random()
        side = (bx - 14) + (by - 30) * 0.3          # 右下ほど影
        if r < 0.22 and side < 0:
            new = lite
        elif r < 0.45 and side > -4:
            new = dark
        else:
            continue
        for k, (x, y) in enumerate(cells):
            if k < 3 or rng.random() < .5:           # 角を1つ欠かして四角く見せない
                g[y][x] = new

GRP = {}
for name, cs in dict(hair='JHhd', skin='Sskr', blouse='Ww', jacket='TtuZ', sleeve='AaX', belt='LY',
                     skirt='PpVvo', legs='gGn', boots='BbK', bag='Mmy').items():
    GRP.update({c: name for c in cs})
Z = dict(legs=0, boots=1, skirt=2, belt=3, jacket=4, sleeve=4.5, blouse=4.6, skin=5, bag=5.2, hair=6)
marks = set()
for y in range(H):
    for x in range(W):
        a = GRP.get(g[y][x])
        for i, j in ((1, 0), (0, 1)):
            if not (x + i < W and y + j < H):
                continue
            b = GRP.get(g[y + j][x + i])
            if not a or not b or a == b or Z[a] == Z[b]:
                continue
            p, q = ((x, y), (x + i, y + j)) if Z[a] < Z[b] else ((x + i, y + j), (x, y))
            if GRP[g[p[1]][p[0]]] == 'skin':
                p = q
            marks.add(p)
for x, y in marks:
    g[y][x] = 'O'

filled = lambda x, y: 0 <= x < W and 0 <= y < H and g[y][x] != '.'
N4 = ((1, 0), (-1, 0), (0, 1), (0, -1))
for x, y in [(x, y) for y in range(H) for x in range(W) if not filled(x, y) and any(filled(x + i, y + j) for i, j in N4)]:
    g[y][x] = 'O'
halo = [(x, y) for y in range(H) for x in range(W) if not filled(x, y) and any(filled(x + i, y + j) for i, j in N4)]


def rgb(h):
    return tuple(int(h[i:i + 2], 16) for i in (1, 3, 5)) + (255,)


img = Image.new('RGBA', (W, H), (0, 0, 0, 0))
for y in range(H):
    for x in range(W):
        if g[y][x] != '.':
            img.putpixel((x, y), rgb(C[g[y][x]]))
img.save('out/chibi_girl.png')
prev = Image.new('RGBA', (W, H), rgb('#eceae1'))
for x, y in halo:
    prev.putpixel((x, y), rgb('#f7f6e6'))
prev.alpha_composite(img)
prev.resize((W * 8, H * 8), Image.NEAREST).save('out/chibi_girl_x8.png')
print(W, H)
