"""1ドットずつ手で置く方式の、右向き（斜め）ちびキャラ。
文字の表 → 色、外側の輪郭と白いふちは自動で足す。
"""
from PIL import Image

C = {
    'O': '#3b0a2a',                                   # 輪郭（こい赤紫）
    'H': '#e8955a', 'h': '#c0603a', 'd': '#7e3230',   # 髪
    'S': '#f8d4b4', 's': '#e8a585', 'k': '#b86a5a', 'r': '#ec8f84',  # 肌・ほほ
    'E': '#f7f6e6', 'e': '#305e6a',                   # 目
    'W': '#f6eedb', 'w': '#d6bfa6',                   # ブラウス
    'T': '#5aa0a0', 't': '#3c7880', 'u': '#285060',   # ケープ
    'L': '#7a3f2a', 'Y': '#e8c060',                   # ベルト
    'P': '#7d4f8f', 'p': '#573468', 'V': '#f6eedb', 'v': '#d6bfa6',                   # スカート
    'g': '#5a4c58', 'G': '#3e3240',                   # タイツ
    'A': '#6fb3b0', 'a': '#41808a', 'B': '#b0683a', 'K': '#d89458', 'n': '#706070', 'o': '#4a2c5c',
    'R': '#c84a3a', 'Q': '#8a2a30', 'C': '#f6eedb', 'c': '#c8b0a0', 'y': '#e8c060', 'M': '#b8743e', 'm': '#6e3a26', 'l': '#6e3a26', 'b': '#70382a',                   # ブーツ
}
ART = r"""
................................
...........hhhh.................
.........hhHHhhhh...............
........hHHHHhhhhhh.............
.......hHHHhhhdhhhhhh...........
......hHHhhhhdhhHHhhh...........
......hHhhhhdhhHHhhhhh..........
.....dhhhhhdhhhhhhdhhhh.........
.....dhhhhdhhhhhhdhhhhhh........
.....dhhhhdhhhhhdhhhShhh........
.....ddhhhdhhhhdhhhSShShh.......
.....dhhhhdhhhdhhSSSSShSh.......
.....dhhhdhhhhhhSSSSSSSSS.......
.....ddhhdhhhhhhSSSSSSSSSS......
......dhhdhhhhkhSSSSSSSSSS......
......ddhdhhhhhssSSSSSSSSSS.....
.......dhdhhhhhsSSSSSSSSS.......
.......dddhhhhhssSSSSSSSs.......
........d.dhhhkssSSSSSs.........
...........dhhkksssss...........
............d.h.kkk.............
..........uTTTTTsRQRAa............
.........uTTTTTTTRQRAAa...........
........uuTTTTTTTQWQAAAa..........
........utTTTTlTtWwAAAAa..........
........uttTTlTTtWwAAAaa..........
........uutTlTTttWwAAAaa..........
.........utlTTTttwAAAaa...........
.........ulttttuwwAAAaa...........
......mMMMMmuuuLLYAAaa............
......mMMyMmPPPLLYLAaa............
......mMMMMmPPPPPPPSSs............
......mMMMMmPPPPPPPsSk............
......mmmmmmPPPPPPPPPpp...........
........PPPPPoPPPPPPPPpp..........
........PPPPPoPPPPPPoPPpp.........
.......PPPPPPoPPPPPPoPPppp........
.......PPPPPoPPPPPPPoPpppp........
......PPPPPPoPPPPPPoPPpppp........
......PPPPPoPPPPPPPoPppppp........
.....PPPPPPoPPPPPPoPPpppppp.......
.....pPPPPoppPPPPPopPpppppp.......
.....VVVVVVVVVVVVVVVVvvvvvv.......
.........GGGG.....gggg............
........GGGG......gggg............
........GGGG.......gggg...........
.......GGGG........nggg...........
.......GGGG.........gggg..........
......GGGG..........gggg..........
......GGGG...........gggg.........
.....KKKKK..........KKKKK.........
.....bBBBb..........bBBBb.........
.....bBBBb..........bBBBBb........
.....bBBBbb.........bBBBBbb.......
....bBBBBBbb........bBBBBBBb......
....bbbbbbbbb.......bbbbbbbbbb....
..................................
"""
# 顔のパーツ（あとからのせる）：(x, y, 文字)
FACE = [(17, 1, 'h'), (18, 0, 'h'),                          # はねた毛
        (15, 9, 'C'), (16, 9, 'C'), (15, 10, 'c'), (16, 10, 'C'),   # ヘアピン
        (4, 17, 'd'), (3, 18, 'd'), (4, 18, 'h'), (5, 19, 'd'),      # うしろ毛のはね
        (23, 12, 'O'),                                               # まつげ
        (9, 31, 'y'),                                  # かばんの金具
(21, 12, 'O'), (22, 12, 'O'), (21, 13, 'O'), (22, 13, 'E'), (21, 14, 'O'), (22, 14, 'e'),
        (19, 11, 'd'), (20, 11, 'd'),                       # まゆ
        (22, 15, 'r'), (23, 15, 'r'), (23, 17, 'k')]        # ほほ・口

rows = [r.ljust(34, '.') for r in ART.strip('\n').split('\n')]
H, W = len(rows), 34
g = [list(r) for r in rows]
for x, y, c in FACE:
    g[y][x] = c


def rgb(h):
    return tuple(int(h[i:i + 2], 16) for i in (1, 3, 5)) + (255,)


filled = lambda x, y: 0 <= x < W and 0 <= y < H and g[y][x] != '.'
N4 = ((1, 0), (-1, 0), (0, 1), (0, -1))
GRP = {**{c: 'hair' for c in 'Hhd'}, **{c: 'skin' for c in 'Sskr'}, **{c: 'blouse' for c in 'Ww'},
       **{c: 'jacket' for c in 'Ttu'}, **{c: 'sleeve' for c in 'Aa'}, **{c: 'belt' for c in 'LY'}, **{c: 'skirt' for c in 'PpVvo'},
       **{c: 'legs' for c in 'gGn'}, **{c: 'boots' for c in 'BbK'}, **{c: 'bag' for c in 'Mm'}}
Z = dict(legs=0, boots=1, skirt=2, belt=3, blouse=4.6, jacket=4, sleeve=4.5, skin=5, bag=5.2, hair=6)
marks = set()
for y in range(H):
    for x in range(W):
        a = GRP.get(g[y][x])
        for i, j in ((1, 0), (0, 1)):
            if not (0 <= x + i < W and 0 <= y + j < H):
                continue
            b = GRP.get(g[y + j][x + i])
            if not a or not b or a == b or Z[a] == Z[b]:
                continue
            p, q = ((x, y), (x + i, y + j)) if Z[a] < Z[b] else ((x + i, y + j), (x, y))
            if GRP[g[p[1]][p[0]]] == 'skin':
                p = q
            marks.add(p)
for x, y in marks:
    g[y][x] = 'O'
# 外側の輪郭
out = [(x, y) for y in range(H) for x in range(W) if not filled(x, y) and any(filled(x + i, y + j) for i, j in N4)]
for x, y in out:
    g[y][x] = 'O'
# いちばん外の白いふち（お手本と同じ）
halo = [(x, y) for y in range(H) for x in range(W) if not filled(x, y) and any(filled(x + i, y + j) and g[y + j][x + i] == 'O' for i, j in N4)]

img = Image.new('RGBA', (W, H), (0, 0, 0, 0))
for y in range(H):
    for x in range(W):
        if g[y][x] != '.':
            img.putpixel((x, y), rgb(C[g[y][x]]))
img.save('out/chibi_girl.png')
prev = Image.new('RGBA', (W, H), rgb('#eceae1'))
for x, y in halo:
    prev.putpixel((x, y), rgb('#f7f6e6'))
prev.alpha_composite(img)
prev.resize((W * 8, H * 8), Image.NEAREST).save('out/chibi_girl_x8.png')
print(W, H)
